# Scratch Work

---

This notebook contains random experiments and notes from following papers and blog posts.

## Tiny Toy Neural Network

---

A tiny neural network implemented in 11 lines of Python. From [this](http://iamtrask.github.io/2015/07/12/basic-python-network/) blog post.

In [11]:
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2 * np.random.random((3,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1
print(f"Initial Values: \n\tX = {X}\n\ty = {y}\n\tsyn0 = {syn0}\n\tsyn1={syn1}")
for i in range(600):
    l1 = 1 / ( 1 + np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2) * (l2 * (1 - l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1 - l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
print(f"Final Results: \n\tsyn0 = {syn0}, \n\tsyn1 = {syn1}")



Initial Values: 
	X = [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
	y = [[0]
 [1]
 [1]
 [0]]
	syn0 = [[ 0.91590545 -0.94806528  0.01695345 -0.18998051]
 [ 0.50698293  0.05162586  0.76641477 -0.97749571]
 [-0.48071356 -0.46834165 -0.78358786 -0.75222207]]
	syn1=[[-0.53169693]
 [ 0.80712138]
 [-0.83193282]
 [-0.3715532 ]]
Final Results: 
	syn0 = [[ 1.46329772 -5.65697579 -0.54339385 -4.92637184]
 [-0.27361715  4.44157279  4.80025337 -4.08926529]
 [ 0.48011106 -2.32243    -1.77436997  1.27635772]], 
	syn1 = [[ 3.02941757]
 [ 6.89873956]
 [-5.27690891]
 [-5.53936796]]
